# Generated by Django 3.2.15 on 2022-11-04 10:21

from django.db import migrations

def update_order_item_price(apps, schema_editor):
    OrderItem = apps.get_model("foodcartapp", "OrderItem")
    Product = apps.get_model("foodcartapp", "Product")

    order_item_set = OrderItem.objects.filter(price=0).select_related("product")
    for order_item in order_item_set.iterator():
        order_item.price = order_item.product.price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(update_order_item_price)
    ]
