# Generated by Django 3.2.15 on 2022-11-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20221104_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RW', 'Не обработан'), ('UA', 'Не собран'), ('UD', 'Не доставлен'), ('CM', 'Выполнен')], db_index=True, default='RW', max_length=2, verbose_name='статус'),
        ),
    ]
