# Generated by Django 3.2.15 on 2022-11-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='время звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='время доставки'),
        ),
    ]
