# Generated by Django 3.2.15 on 2022-11-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20221107_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CH', 'Наличкой'), ('ON', 'На сайте')], default='CH', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
