# Generated by Django 3.2.15 on 2022-11-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CH', 'Наличкой'), ('ON', 'На сайте')], db_index=True, default='CH', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
