# Generated by Django 3.2.15 on 2022-11-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20221107_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CH', 'Наличностью'), ('ON', 'Электронно')], db_index=True, default='CH', max_length=2, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RW', 'Необработанный'), ('CK', 'Готовится'), ('DL', 'Доставляется'), ('CM', 'Выполнен')], db_index=True, default='RW', max_length=2, verbose_name='статус'),
        ),
    ]
