# Generated by Django 3.2.15 on 2022-11-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20221107_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UW', 'Необработанный'), ('CK', 'Готовится'), ('DL', 'Доставляется'), ('CM', 'Выполнен')], db_index=True, default='UW', max_length=2, verbose_name='статус'),
        ),
    ]
