# Generated by Django 3.2.15 on 2022-11-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Необработанный'), ('2', 'Готовится'), ('3', 'Доставляется'), ('4', 'Выполнен')], db_index=True, default='1', max_length=2, verbose_name='статус'),
        ),
    ]
